### ISSUE TITLE
need tests: sort by result in runtests (while executing a test run)

### ISSUE THREAD

**Issue by camd** [mozilla/moztrap-tests#117]
We should ensure the sorting is correct when a test run has multiple possible environments and users.

1. submit results with multiple users on different cases for same environment.  Sorting should honor results from both (i.e.: passes from one user grouped with passes from the other user,etc).
2. submit results from the same or different users on different environments for the run.  Sorting should only group passes, fails, etc from existing environment, and ignore results for other environments

**Comment by davehunt** [comment]
Closing this to concentrate community involvement on more valuable issues.
