### ISSUE TITLE
Investigate why we don't always click the Persona Sign In button

### ISSUE THREAD

**Issue by stephendonner** [mozilla/moztrap-tests#149]
This might be a BIDPOM thing, but at least both MozTrap staging and dev test suites, we often fail to click the Sign In button; see http://screencast.com/t/qSuyIMGI

**Comment by rbillings** [comment]
There hasn't been an issue with this in the last 2 months. @stephendonner should this be closed?

**Comment by stephendonner** [comment]
Yeah, let's close this -- thanks for asking, @rbillings
