### ISSUE TITLE
Investigate/fix MozTrap tests which rely on the auth API, etc.

### ISSUE THREAD

**Issue by stephendonner** [mozilla/moztrap-tests#158]
In the path to upgrading Django, there were auth API changes, here: https://github.com/mozilla/moztrap/commit/d311bf76faefc50a17ae7c4f545eff66017e3a98

I believe this is what's causing the majority of the test failures here, on staging: https://webqa-ci.mozilla.com/view/MozTrap/job/moztrap.stage.saucelabs/82/

Some examples:
1) test_creating_a_tag_with_a_product_value_and_cases:
tests/test_manage_tags_page.py:54: in test_creating_a_tag_with_a_product_value_and_cases
>       cases = self.create_bulk_cases(mozwebqa_logged_in, product, use_API=True)
pages/base_test.py:177: in create_bulk_cases
>               api.create_case(case, product)
mocks/moztrap_api.py:183: in create_case
>       case['id'] = self._do_post(uri, post_data)
mocks/moztrap_api.py:31: in _do_post
>       response.raise_for_status()
.env/lib/python2.7/site-packages/requests/models.py:825: in raise_for_status
>           raise HTTPError(http_error_msg, response=self)
E           HTTPError: 400 Client Error: BAD REQUEST

2) test_that_user_can_create_and_delete_run:
def fin():
        if hasattr(request, 'product'):
>           api.delete_product(request.product)

conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mocks.moztrap_api.MoztrapAPI instance at 0x7fdd8b309f38>
product = {'description': u'This is a test product created on 2015-03-23T22:43:01.860966...on/133343/'}, 'id': 106491, 'name': u'Test Product 2015-03-23T22:43:01.860966'}

    def delete_product(self, product):
    
        uri = "api/v1/product"
        self.params['permanent'] = True
>       Assert.true(self._do_delete(uri, product['id']), 'Deletion of product %s failed' % product['name'])

mocks/moztrap_api.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <class 'unittestzero.Assert'>, first = False
msg = u'Deletion of product Test Product 2015-03-23T22:43:01.860966 failed'

    @classmethod
    def true(self, first, msg=None):
        """
            Asserts that what is given is equal to True
    
            :Args:
             - First object to be tested
             - Message that will be printed if it fails
            """
    
>       assert bool(first) is True, msg
E       AssertionError: Deletion of product Test Product 2015-03-23T22:43:01.860966 failed

.env/lib/python2.7/site-packages/unittestzero.py:79: AssertionError

**Comment by stephendonner** [comment]
@bobsilverberg @camd @peterbe - can you work together on this?  Thanks!

**Comment by bobsilverberg** [comment]
@peterbe Do you know if anything about the way we need to call the API would have changed?

**Comment by peterbe** [comment]
One early comment that I do know for sure is that the old django and tastypie used to return IDs as strings. E.g. `{"productversion_id": "123"}` when it now instead returns `{"productversion_id": 123}`. 

I'm actively investigating the 204 status codes now being 200 on deletes.

**Comment by peterbe** [comment]
Right, apart from the new thing about IDs being integers now, [204s should be 200s](https://github.com/mozilla/moztrap-tests/pull/159#issuecomment-85545071).

**Comment by bobsilverberg** [comment]
I merged in PR #159, which might resolve all the issues. Let's keep this open until we get a green run to make sure.

**Comment by peterbe** [comment]
Merging that, does that automatically re-run the tests?

**Comment by rbillings** [comment]
This has been green since late March, closing the issue.
