### ISSUE TITLE
Add a setup.cfg file to configure the behaviour of flake8

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/moztrap-tests#164]
This is a simple task: 

1. Add a new file to the repo called `setup.cfg`. The file should look just like the file found at https://github.com/mozilla/mcom-tests/blob/master/setup.cfg
2. Update the `.travis.yml` file so the `script:` line reads:
```yml
script: "flake8 ."
```

**Comment by IamAdiSri** [comment]
Where do i need to place the setup.cfg file?
Thanks!

**Comment by bobsilverberg** [comment]
Fixed via https://github.com/mozilla/moztrap-tests/commit/a9bee504a6b9ac01d44069c49c55d27e04349cd2
