### ISSUE TITLE
Switch to persona test users

### ISSUE THREAD

**Issue by davehunt** [mozilla/moztrap-tests#168]
We're currently using credentials stored on disk, however MozTrap uses Persona for login. We should look into switching to the persona test user API.

**Comment by davehunt** [comment]
I played with this a little while working on #167, and might have bundled the change in there if it wasn't for one thing: MozTrap prompts new users for a username. We would either need to handle this in our login method, or (ideally) set the username via an API call. @camd is there such an API?

**Comment by rbillings** [comment]
I just confirmed that there is no way to handle it via an API call. @camd said it'd be fairly simple to add it, if you are familiar with tastypie.

**Comment by davehunt** [comment]
Let's open an issue against MozTrap with this enhancement request. If @camd could provide some pointers, perhaps someone would consider picking this up, and we can mark it as a blocker here.

**Comment by davehunt** [comment]
Closing this to concentrate community involvement on more valuable issues.
