### ISSUE TITLE
Remove reruns from the job and address any intermittents that appear

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/moztrap-tests#169]
I tried to remove reruns from the moztrap.stage.saucelabs job, but the job ended up failing almost continuously, but with different tests failing. We do want to eventually remove reruns, but if we do that we also have to commit to addressing any and all intermittents that occur, and we can be fairly certain there will be a number of those.

**Comment by davehunt** [comment]
Closing this to concentrate community involvement on more valuable issues.
