### ISSUE TITLE
Find a way to cleanup environment categories after or between test runs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/moztrap-tests#173]
There was a bug with Moztrap stage [1] which was resolved by @camd manually deleting some environment categories as documented in the following conversation between @stephendonner and @camd:

```
3:42:58 PM <camd> stephend|appt: hey, so I soft-delete several hundred environment categories by hand  (up to june this year) and now the "create profile" page will load
3:43:05 PM <camd> slowly, because there are still many hundreds.
3:43:20 PM <camd> but that test may pass now, fwiw.  And sounds like a cleanup script would help a lot.
```

So it looks like we either need to enhance the tests to automatically delete environment categories (as is currently done with products, versions, etc.), or create a cleanup script that can run periodically to remove them. The latter may be necessary if the API does not exist which would allow us to do the cleanup via the API which is what we're doing with other items.

**Comment by bobsilverberg** [comment]
I discussed this with @camd today and we decided that the best way to address this would be by adding a management command to moztrap itself that can be used to do the cleanup. It would target particular model instances that are created by our tests and delete them. It could be scheduled to run as a cron job to do a regular cleanup.

**Comment by bobsilverberg** [comment]
I opened https://github.com/mozilla/moztrap/pull/102 to address this issue.

**Comment by bobsilverberg** [comment]
This change landed in https://github.com/mozilla/moztrap/commit/0322e1c51fe07cc9707a687ab309a00ca374a1af. The only item left is to schedule the command to be run via a cron job and @camd has offered to do that, likely next week.

**Comment by stephendonner** [comment]
Huge thanks to both @bobsilverberg and @camd :+1:
