### ISSUE TITLE
Migrate from browserid to bidpom

### ISSUE THREAD

**Issue by davehunt** [mozilla/moztrap-tests#181]
Due to conflicts with another package, the [browserid](https://pypi.python.org/pypi/browserid) package was renamed to [bidpom](https://pypi.python.org/pypi/bidpom/). This suite should be updated to use the new package. This involves changing the dependency name in `requirements.txt` and updating the use of the package to the new package structure. Documentation with examples for bidpom can be found [here](https://github.com/mozilla/bidpom/wiki/Examples-of-integrating-BIDPOM).

This issue is a suitable [Outreachy application contribution](https://github.com/davehunt/pytest-html#outreachy).

**Comment by carcablop** [comment]
Hello.I would like to participate in this task to implement the project Outreachy. Is it still open?

**Comment by davehunt** [comment]
Hey @carcablop, yes it's still available. I'll assign it to you.

**Comment by carcablop** [comment]
Hi @davehunt, to run a test I need to modify the file variables.json and add vouched and privated users? How can I get those users ?, My account does not allow me to vouch, but someone else tells me I should make a vouched. my account is as follows: https://mozillians.allizom.org/es/u/carcablop/

Thanks

**Comment by davehunt** [comment]
@carcablop you don't need a vouched Mozillians user to run the MozTrap tests. You just need a standard Persona user, which you can create through the [login process](https://moztrap.allizom.org/users/login/). You'll then need to add these credentials to a JSON file, which you will reference on the command line. See [the README](https://github.com/mozilla/moztrap-tests#create-a-test-user) for more information.

**Comment by davehunt** [comment]
@carcablop are you still interested in working on this issue?

**Comment by carcablop** [comment]
Hi @davehunt, I still interested in working on this issue, but i would like to know what are the steps to keep working?. I had problems when I run the test.
Times where I can work on this task are from 5:00 a.m. to 9:00 a.m (Colombian time), I guess 12 am to 4 pm (UK time). Thanks very much

**Comment by davehunt** [comment]
@carcablop did https://github.com/mozilla/moztrap-tests/issues/181#issuecomment-197811884 not help? Do you have any specific questions or errors that you are encountering?

**Comment by davehunt** [comment]
Are you still intending to work on this @carcablop or should we release it for someone else to pick up?

**Comment by davehunt** [comment]
Are you still intending to work on this @stephendonner?

**Comment by stephendonner** [comment]
@davehunt sorry for the inaction/delay.  Yes, and hopefully I've cleanly fixed it!  r?  https://github.com/mozilla/moztrap-tests/pull/187
