### ISSUE TITLE
Update link from mozwebqa-test-templates repo to mozwebqa-examples repo in README.md

### ISSUE THREAD

**Issue by stephendonner** [mozilla/moztrap-tests#184]
We need to update the link to https://github.com/mozilla/mozwebqa-test-templates in the README to point to https://github.com/mozilla/mozwebqa-examples instead.

**Comment by davehunt** [comment]
I can't find a reference to mozwebqa-test-templates in the README.

**Comment by stephendonner** [comment]
Got the wrong repo, sorry; closing out (just a few have the old readme link).
